#!/usr/bin/env bash

# . ./commands/project/run_all_baselines

python ./main/run/full.py -- @ENV=LUNAR   @LOSS=BASELINE experiment_name:final_1 predictor_settings:force_recompute:true
python ./main/run/full.py -- @ENV=HOPPER  @LOSS=BASELINE experiment_name:final_1 predictor_settings:force_recompute:true
python ./main/run/full.py -- @ENV=CHEETAH @LOSS=BASELINE experiment_name:final_1 predictor_settings:force_recompute:true
python ./main/run/full.py -- @ENV=WALKER  @LOSS=BASELINE experiment_name:final_1 predictor_settings:force_recompute:true
python ./main/run/full.py -- @ENV=ANT     @LOSS=BASELINE experiment_name:final_1 predictor_settings:force_recompute:true
python ./main/run/full.py -- @ENV=REACHER @LOSS=BASELINE experiment_name:final_1 predictor_settings:force_recompute:true