#!/usr/bin/env bash

python ./main/run/full.py -- @CUSTOM=CHEETAH_BASELINE               experiment_name:baseline_2
python ./main/run/full.py -- @CUSTOM=CHEETAH_Q                      experiment_name:q_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_Q_PLUS_STATE           experiment_name:q_plus_state_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_Q_UNFAVORED_PLUS_STATE experiment_name:q_unfavored_plus_state_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_Q_IGNORED_PLUS_STATE   experiment_name:q_ignored_plus_state_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_CONSISTENT_COACH       experiment_name:consistent_coach_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_CONSISTENT_VALUE       experiment_name:consistent_value_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_HALF_CONSISTENT_COACH  experiment_name:half_consistent_coach_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_STATE_TRIPLE           experiment_name:state_triple_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_DELAYED_COACH_LOSS     experiment_name:delayed_coach_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_HALF_CONSISTENT_COACH  experiment_name:half_consistent_coach_loss_1
python ./main/run/full.py -- @CUSTOM=CHEETAH_DELAYED_COACH          experiment_name:delayed_coach_loss_1