#!/usr/bin/env bash

# commands/project/run_all data/logs/state_loss_2/LunarLanderContinuous-v2  experiment_name:state_loss_2 'env_names:["LunarLanderContinuous-v2"]' train_coach:loss_style:batched train_coach:loss_function:state_prediction_loss
# commands/project/run_all data/logs/coach_loss_1/LunarLanderContinuous-v2  experiment_name:coach_loss_1 'env_names:["LunarLanderContinuous-v2"]' train_coach:loss_style:timestep train_coach:loss_function:consistent_coach_loss
# commands/project/run_all data/logs/coach_loss_2/LunarLanderContinuous-v2  experiment_name:coach_loss_2 'env_names:["LunarLanderContinuous-v2"]' train_coach:loss_style:timestep train_coach:loss_function:consistent_coach_loss

# commands/project/run_all data/logs/state_loss_2/MountainCarContinuous-v0  experiment_name:state_loss_2 'env_names:["MountainCarContinuous-v0"]' train_coach:loss_style:batched train_coach:loss_function:state_prediction_loss
# commands/project/run_all data/logs/coach_loss_1/MountainCarContinuous-v0  experiment_name:coach_loss_1 'env_names:["MountainCarContinuous-v0"]' train_coach:loss_style:timestep train_coach:loss_function:consistent_coach_loss
# commands/project/run_all data/logs/coach_loss_2/MountainCarContinuous-v0  experiment_name:coach_loss_2 'env_names:["MountainCarContinuous-v0"]' train_coach:loss_style:timestep train_coach:loss_function:consistent_coach_loss

# commands/project/run_all data/logs/state_loss_1/HopperBulletEnv-v0  experiment_name:state_loss_1 'env_names:["HopperBulletEnv-v0"]' train_coach:loss_style:batched train_coach:loss_function:state_prediction_loss
# commands/project/run_all data/logs/coach_loss_1/HopperBulletEnv-v0  experiment_name:coach_loss_1 'env_names:["HopperBulletEnv-v0"]' train_coach:loss_style:timestep train_coach:loss_function:consistent_coach_loss

commands/project/run_all data/logs/state_loss_1/AntBulletEnv-v0  experiment_name:state_loss_1 'env_names:["AntBulletEnv-v0"]' train_coach:loss_style:batched train_coach:loss_function:state_prediction_loss
commands/project/run_all data/logs/coach_loss_1/AntBulletEnv-v0  experiment_name:coach_loss_1 'env_names:["AntBulletEnv-v0"]' train_coach:loss_style:timestep train_coach:loss_function:consistent_coach_loss

commands/project/run_all data/logs/state_loss_1/BipedalWalker-v3  experiment_name:state_loss_1 'env_names:["BipedalWalker-v3"]' train_coach:loss_style:batched train_coach:loss_function:state_prediction_loss
commands/project/run_all data/logs/coach_loss_1/BipedalWalker-v3  experiment_name:coach_loss_1 'env_names:["BipedalWalker-v3"]' train_coach:loss_style:timestep train_coach:loss_function:consistent_coach_loss

commands/project/run_all data/logs/state_loss_1/HalfCheetahBulletEnv-v0  experiment_name:state_loss_1 'env_names:["HalfCheetahBulletEnv-v0"]' train_coach:loss_style:batched train_coach:loss_function:state_prediction_loss
commands/project/run_all data/logs/coach_loss_1/HalfCheetahBulletEnv-v0  experiment_name:coach_loss_1 'env_names:["HalfCheetahBulletEnv-v0"]' train_coach:loss_style:timestep train_coach:loss_function:consistent_coach_loss