#!/usr/bin/env bash


python ./main/run/full.py -- \
    train_coach:force_retrain:"false" \
    test_predictor:force_recompute:"false" \
    env_name:"AntBulletEnv-v0" \
    experiment_name:"baseline_1"

# 
# consistent_value_loss
# 
python ./main/run/full.py -- \
    train_coach:force_retrain:"false" \
    test_predictor:force_recompute:"false" \
    env_name:"AntBulletEnv-v0" \
    experiment_name:"consistent_value_loss_1" \
    train_coach:loss_function:"consistent_value_loss"

# 
# consistent_coach_loss
# 
python ./main/run/full.py -- \
    train_coach:force_retrain:"false" \
    test_predictor:force_recompute:"false" \
    env_name:"AntBulletEnv-v0" \
    experiment_name:"consistent_coach_loss_1" \
    train_coach:loss_function:"consistent_coach_loss" \
    train_coach:consistent_coach_loss:scale_future_state_loss:"1"

# 
# half_consistent_coach_loss
# 
python ./main/run/full.py -- \
    train_coach:force_retrain:"false" \
    test_predictor:force_recompute:"false" \
    env_name:"AntBulletEnv-v0" \
    experiment_name:"half_consistent_coach_loss_1" \
    train_coach:loss_function:"half_consistent_coach_loss" \
    train_coach:consistent_coach_loss:scale_future_state_loss:"1" \
    # train_coach:number_of_epochs:500

# 
# state_triple_loss
# 
python ./main/run/full.py -- \
    train_coach:force_retrain:"false" \
    test_predictor:force_recompute:"false" \
    env_name:"AntBulletEnv-v0" \
    experiment_name:"state_triple_loss_1" \
    train_coach:loss_function:"state_triple_loss" \
    train_coach:consistent_coach_loss:scale_future_state_loss:"1" \
    # train_coach:number_of_epochs:500

python ./main/run/full.py -- \
    train_coach:force_retrain:"false" \
    test_predictor:force_recompute:"false" \
    env_name:"AntBulletEnv-v0" \
    experiment_name:"state_triple_loss_2" \
    train_coach:loss_function:"state_triple_loss" \
    train_coach:consistent_coach_loss:scale_future_state_loss:"1" \
    train_coach:number_of_epochs:500

# 
# delayed
# 
python ./main/run/full.py -- \
    train_coach:force_retrain:"false" \
    test_predictor:force_recompute:"false" \
    env_name:"AntBulletEnv-v0" \
    experiment_name:"delayed_coach_loss_1" \
    train_coach:loss_function:"delayed_coach_loss" \
    train_coach:consistent_coach_loss:scale_future_state_loss:"1" \
    train_coach:number_of_epochs:120 \
    train_coach:batch_size:256