#!/usr/bin/env bash

python ./main/run/full.py -- experiment_name:state_loss_1_with_sac4

# commands/project/run_all data/logs/state_loss_1/HopperBulletEnv-v0  experiment_name:state_loss_1 'env_name=HopperBulletEnv-v0' train_coach:loss_api:batched train_coach:loss_function:state_prediction_loss
# commands/project/run_all data/logs/coach_loss_1/HopperBulletEnv-v0  experiment_name:coach_loss_1 'env_name=HopperBulletEnv-v0' train_coach:loss_api:timestep train_coach:loss_function:consistent_coach_loss

# commands/project/run_all data/logs/state_loss_1/AntBulletEnv-v0  experiment_name:state_loss_1 'env_name=AntBulletEnv-v0' train_coach:loss_api:batched train_coach:loss_function:state_prediction_loss
# commands/project/run_all data/logs/coach_loss_1/AntBulletEnv-v0  experiment_name:coach_loss_1 'env_name=AntBulletEnv-v0' train_coach:loss_api:timestep train_coach:loss_function:consistent_coach_loss

# commands/project/run_all data/logs/state_loss_1/BipedalWalker-v3  experiment_name:state_loss_1 'env_name=BipedalWalker-v3' train_coach:loss_api:batched train_coach:loss_function:state_prediction_loss
# commands/project/run_all data/logs/coach_loss_1/BipedalWalker-v3  experiment_name:coach_loss_1 'env_name=BipedalWalker-v3' train_coach:loss_api:timestep train_coach:loss_function:consistent_coach_loss

# commands/project/run_all data/logs/state_loss_1/HalfCheetahBulletEnv-v0  experiment_name:state_loss_1 'env_name=HalfCheetahBulletEnv-v0' train_coach:loss_api:batched train_coach:loss_function:state_prediction_loss
# commands/project/run_all data/logs/coach_loss_1/HalfCheetahBulletEnv-v0  experiment_name:coach_loss_1 'env_name=HalfCheetahBulletEnv-v0' train_coach:loss_api:timestep train_coach:loss_function:consistent_coach_loss