#!/usr/bin/env bash

# stdbuf -i0 -o0 -e0 ./commands/project/run_ant 2>&1 | tee logs/run_ant.log

mkdir -p logs/ant
# this one trains the agent that all the others will use
python ./main/run/full.py -- @CUSTOM=ANT_BASELINE               experiment_name:baseline_2 1>&2 | tee logs/ant/baseline_2.log

python ./main/run/full.py -- @CUSTOM=ANT_Q                      experiment_name:q_loss_1                      "$@" &> logs/ant/q_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_Q_PLUS_STATE           experiment_name:q_plus_state_loss_1           "$@" &> logs/ant/q_plus_state_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_Q_UNFAVORED_PLUS_STATE experiment_name:q_unfavored_plus_state_loss_1 "$@" &> logs/ant/q_unfavored_plus_state_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_Q_IGNORED_PLUS_STATE   experiment_name:q_ignored_plus_state_loss_1   "$@" &> logs/ant/q_ignored_plus_state_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_CONSISTENT_COACH       experiment_name:consistent_coach_loss_1       "$@" &> logs/ant/consistent_coach_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_CONSISTENT_VALUE       experiment_name:consistent_value_loss_1       "$@" &> logs/ant/consistent_value_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_HALF_CONSISTENT_COACH  experiment_name:half_consistent_coach_loss_1  "$@" &> logs/ant/half_consistent_coach_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_STATE_TRIPLE           experiment_name:state_triple_1                "$@" &> logs/ant/state_triple_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_DELAYED_COACH_LOSS     experiment_name:delayed_coach_loss_1          "$@" &> logs/ant/delayed_coach_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_HALF_CONSISTENT_COACH  experiment_name:half_consistent_coach_loss_1  "$@" &> logs/ant/half_consistent_coach_loss_1.log &
python ./main/run/full.py -- @CUSTOM=ANT_DELAYED_COACH          experiment_name:delayed_coach_loss_1          "$@" &> logs/ant/delayed_coach_loss_1.log &